// Code generated by go-swagger; DO NOT EDIT.

package pipelinerunlog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// GetPipelineRunLogsReader is a Reader for the GetPipelineRunLogs structure.
type GetPipelineRunLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineRunLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineRunLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPipelineRunLogsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPipelineRunLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPipelineRunLogsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPipelineRunLogsOK creates a GetPipelineRunLogsOK with default headers values
func NewGetPipelineRunLogsOK() *GetPipelineRunLogsOK {
	return &GetPipelineRunLogsOK{}
}

/*
GetPipelineRunLogsOK describes a response with status code 200, with default header values.

OK
*/
type GetPipelineRunLogsOK struct {
	Payload []*models.PipelineRunLog
}

func (o *GetPipelineRunLogsOK) Error() string {
	return fmt.Sprintf("[GET /admin/logs/{pipeline_run_id}][%d] getPipelineRunLogsOK  %+v", 200, o.Payload)
}
func (o *GetPipelineRunLogsOK) GetPayload() []*models.PipelineRunLog {
	return o.Payload
}

func (o *GetPipelineRunLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineRunLogsBadRequest creates a GetPipelineRunLogsBadRequest with default headers values
func NewGetPipelineRunLogsBadRequest() *GetPipelineRunLogsBadRequest {
	return &GetPipelineRunLogsBadRequest{}
}

/*
GetPipelineRunLogsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetPipelineRunLogsBadRequest struct {
	Payload interface{}
}

func (o *GetPipelineRunLogsBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/logs/{pipeline_run_id}][%d] getPipelineRunLogsBadRequest  %+v", 400, o.Payload)
}
func (o *GetPipelineRunLogsBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *GetPipelineRunLogsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineRunLogsNotFound creates a GetPipelineRunLogsNotFound with default headers values
func NewGetPipelineRunLogsNotFound() *GetPipelineRunLogsNotFound {
	return &GetPipelineRunLogsNotFound{}
}

/*
GetPipelineRunLogsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetPipelineRunLogsNotFound struct {
	Payload interface{}
}

func (o *GetPipelineRunLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/logs/{pipeline_run_id}][%d] getPipelineRunLogsNotFound  %+v", 404, o.Payload)
}
func (o *GetPipelineRunLogsNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *GetPipelineRunLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineRunLogsInternalServerError creates a GetPipelineRunLogsInternalServerError with default headers values
func NewGetPipelineRunLogsInternalServerError() *GetPipelineRunLogsInternalServerError {
	return &GetPipelineRunLogsInternalServerError{}
}

/*
GetPipelineRunLogsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetPipelineRunLogsInternalServerError struct {
	Payload interface{}
}

func (o *GetPipelineRunLogsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/logs/{pipeline_run_id}][%d] getPipelineRunLogsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetPipelineRunLogsInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *GetPipelineRunLogsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
