// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ListRegistryReader is a Reader for the ListRegistry structure.
type ListRegistryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRegistryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRegistryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListRegistryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListRegistryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListRegistryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListRegistryOK creates a ListRegistryOK with default headers values
func NewListRegistryOK() *ListRegistryOK {
	return &ListRegistryOK{}
}

/*
ListRegistryOK describes a response with status code 200, with default header values.

OK
*/
type ListRegistryOK struct {

	/* total matching count
	 */
	XTotalCount int64

	Payload *models.RegistryList
}

func (o *ListRegistryOK) Error() string {
	return fmt.Sprintf("[GET /admin/registry][%d] listRegistryOK  %+v", 200, o.Payload)
}
func (o *ListRegistryOK) GetPayload() *models.RegistryList {
	return o.Payload
}

func (o *ListRegistryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := swag.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	o.Payload = new(models.RegistryList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRegistryBadRequest creates a ListRegistryBadRequest with default headers values
func NewListRegistryBadRequest() *ListRegistryBadRequest {
	return &ListRegistryBadRequest{}
}

/*
ListRegistryBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListRegistryBadRequest struct {
	Payload interface{}
}

func (o *ListRegistryBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/registry][%d] listRegistryBadRequest  %+v", 400, o.Payload)
}
func (o *ListRegistryBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ListRegistryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRegistryNotFound creates a ListRegistryNotFound with default headers values
func NewListRegistryNotFound() *ListRegistryNotFound {
	return &ListRegistryNotFound{}
}

/*
ListRegistryNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListRegistryNotFound struct {
	Payload interface{}
}

func (o *ListRegistryNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/registry][%d] listRegistryNotFound  %+v", 404, o.Payload)
}
func (o *ListRegistryNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ListRegistryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRegistryInternalServerError creates a ListRegistryInternalServerError with default headers values
func NewListRegistryInternalServerError() *ListRegistryInternalServerError {
	return &ListRegistryInternalServerError{}
}

/*
ListRegistryInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListRegistryInternalServerError struct {
	Payload interface{}
}

func (o *ListRegistryInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/registry][%d] listRegistryInternalServerError  %+v", 500, o.Payload)
}
func (o *ListRegistryInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ListRegistryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
