// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEnvironmentListParams creates a new EnvironmentListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEnvironmentListParams() *EnvironmentListParams {
	return &EnvironmentListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEnvironmentListParamsWithTimeout creates a new EnvironmentListParams object
// with the ability to set a timeout on a request.
func NewEnvironmentListParamsWithTimeout(timeout time.Duration) *EnvironmentListParams {
	return &EnvironmentListParams{
		timeout: timeout,
	}
}

// NewEnvironmentListParamsWithContext creates a new EnvironmentListParams object
// with the ability to set a context for a request.
func NewEnvironmentListParamsWithContext(ctx context.Context) *EnvironmentListParams {
	return &EnvironmentListParams{
		Context: ctx,
	}
}

// NewEnvironmentListParamsWithHTTPClient creates a new EnvironmentListParams object
// with the ability to set a custom HTTPClient for a request.
func NewEnvironmentListParamsWithHTTPClient(client *http.Client) *EnvironmentListParams {
	return &EnvironmentListParams{
		HTTPClient: client,
	}
}

/*
EnvironmentListParams contains all the parameters to send to the API endpoint

	for the environment list operation.

	Typically these are written to a http.Request.
*/
type EnvironmentListParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* End.

	   end
	*/
	End *int64

	/* Order.

	   sort order
	*/
	Order *string

	/* Sort.

	   sort column
	*/
	Sort *string

	/* Start.

	   start
	*/
	Start *int64

	/* ID.

	   id filter
	*/
	ID *string

	/* Name.

	   name filter
	*/
	Name *string

	/* NameSlug.

	   find by environment name
	*/
	NameSlug *string

	/* Q.

	   query keyword filter
	*/
	Q *string

	/* RegistryID.

	   registry id
	*/
	RegistryID *string

	/* RepositoryID.

	   filter by repository_id
	*/
	RepositoryID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the environment list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnvironmentListParams) WithDefaults() *EnvironmentListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the environment list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnvironmentListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the environment list params
func (o *EnvironmentListParams) WithTimeout(timeout time.Duration) *EnvironmentListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the environment list params
func (o *EnvironmentListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the environment list params
func (o *EnvironmentListParams) WithContext(ctx context.Context) *EnvironmentListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the environment list params
func (o *EnvironmentListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the environment list params
func (o *EnvironmentListParams) WithHTTPClient(client *http.Client) *EnvironmentListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the environment list params
func (o *EnvironmentListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the environment list params
func (o *EnvironmentListParams) WithXWorkspaceID(xWorkspaceID string) *EnvironmentListParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the environment list params
func (o *EnvironmentListParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithEnd adds the end to the environment list params
func (o *EnvironmentListParams) WithEnd(end *int64) *EnvironmentListParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the environment list params
func (o *EnvironmentListParams) SetEnd(end *int64) {
	o.End = end
}

// WithOrder adds the order to the environment list params
func (o *EnvironmentListParams) WithOrder(order *string) *EnvironmentListParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the environment list params
func (o *EnvironmentListParams) SetOrder(order *string) {
	o.Order = order
}

// WithSort adds the sort to the environment list params
func (o *EnvironmentListParams) WithSort(sort *string) *EnvironmentListParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the environment list params
func (o *EnvironmentListParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithStart adds the start to the environment list params
func (o *EnvironmentListParams) WithStart(start *int64) *EnvironmentListParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the environment list params
func (o *EnvironmentListParams) SetStart(start *int64) {
	o.Start = start
}

// WithID adds the id to the environment list params
func (o *EnvironmentListParams) WithID(id *string) *EnvironmentListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the environment list params
func (o *EnvironmentListParams) SetID(id *string) {
	o.ID = id
}

// WithName adds the name to the environment list params
func (o *EnvironmentListParams) WithName(name *string) *EnvironmentListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the environment list params
func (o *EnvironmentListParams) SetName(name *string) {
	o.Name = name
}

// WithNameSlug adds the nameSlug to the environment list params
func (o *EnvironmentListParams) WithNameSlug(nameSlug *string) *EnvironmentListParams {
	o.SetNameSlug(nameSlug)
	return o
}

// SetNameSlug adds the nameSlug to the environment list params
func (o *EnvironmentListParams) SetNameSlug(nameSlug *string) {
	o.NameSlug = nameSlug
}

// WithQ adds the q to the environment list params
func (o *EnvironmentListParams) WithQ(q *string) *EnvironmentListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the environment list params
func (o *EnvironmentListParams) SetQ(q *string) {
	o.Q = q
}

// WithRegistryID adds the registryID to the environment list params
func (o *EnvironmentListParams) WithRegistryID(registryID *string) *EnvironmentListParams {
	o.SetRegistryID(registryID)
	return o
}

// SetRegistryID adds the registryId to the environment list params
func (o *EnvironmentListParams) SetRegistryID(registryID *string) {
	o.RegistryID = registryID
}

// WithRepositoryID adds the repositoryID to the environment list params
func (o *EnvironmentListParams) WithRepositoryID(repositoryID *string) *EnvironmentListParams {
	o.SetRepositoryID(repositoryID)
	return o
}

// SetRepositoryID adds the repositoryId to the environment list params
func (o *EnvironmentListParams) SetRepositoryID(repositoryID *string) {
	o.RepositoryID = repositoryID
}

// WriteToRequest writes these params to a swagger request
func (o *EnvironmentListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}

	if o.End != nil {

		// query param _end
		var qrEnd int64

		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := swag.FormatInt64(qrEnd)
		if qEnd != "" {

			if err := r.SetQueryParam("_end", qEnd); err != nil {
				return err
			}
		}
	}

	if o.Order != nil {

		// query param _order
		var qrOrder string

		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {

			if err := r.SetQueryParam("_order", qOrder); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param _sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("_sort", qSort); err != nil {
				return err
			}
		}
	}

	if o.Start != nil {

		// query param _start
		var qrStart int64

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt64(qrStart)
		if qStart != "" {

			if err := r.SetQueryParam("_start", qStart); err != nil {
				return err
			}
		}
	}

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.NameSlug != nil {

		// query param name_slug
		var qrNameSlug string

		if o.NameSlug != nil {
			qrNameSlug = *o.NameSlug
		}
		qNameSlug := qrNameSlug
		if qNameSlug != "" {

			if err := r.SetQueryParam("name_slug", qNameSlug); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.RegistryID != nil {

		// query param registry_id
		var qrRegistryID string

		if o.RegistryID != nil {
			qrRegistryID = *o.RegistryID
		}
		qRegistryID := qrRegistryID
		if qRegistryID != "" {

			if err := r.SetQueryParam("registry_id", qRegistryID); err != nil {
				return err
			}
		}
	}

	if o.RepositoryID != nil {

		// query param repository_id
		var qrRepositoryID string

		if o.RepositoryID != nil {
			qrRepositoryID = *o.RepositoryID
		}
		qRepositoryID := qrRepositoryID
		if qRepositoryID != "" {

			if err := r.SetQueryParam("repository_id", qRepositoryID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
