// Code generated by go-swagger; DO NOT EDIT.

package variables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// NewCreateVariableParams creates a new CreateVariableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateVariableParams() *CreateVariableParams {
	return &CreateVariableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVariableParamsWithTimeout creates a new CreateVariableParams object
// with the ability to set a timeout on a request.
func NewCreateVariableParamsWithTimeout(timeout time.Duration) *CreateVariableParams {
	return &CreateVariableParams{
		timeout: timeout,
	}
}

// NewCreateVariableParamsWithContext creates a new CreateVariableParams object
// with the ability to set a context for a request.
func NewCreateVariableParamsWithContext(ctx context.Context) *CreateVariableParams {
	return &CreateVariableParams{
		Context: ctx,
	}
}

// NewCreateVariableParamsWithHTTPClient creates a new CreateVariableParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateVariableParamsWithHTTPClient(client *http.Client) *CreateVariableParams {
	return &CreateVariableParams{
		HTTPClient: client,
	}
}

/*
CreateVariableParams contains all the parameters to send to the API endpoint

	for the create variable operation.

	Typically these are written to a http.Request.
*/
type CreateVariableParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* Request.

	   create variable request
	*/
	Request *models.CreateVariableRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create variable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVariableParams) WithDefaults() *CreateVariableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create variable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVariableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create variable params
func (o *CreateVariableParams) WithTimeout(timeout time.Duration) *CreateVariableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create variable params
func (o *CreateVariableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create variable params
func (o *CreateVariableParams) WithContext(ctx context.Context) *CreateVariableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create variable params
func (o *CreateVariableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create variable params
func (o *CreateVariableParams) WithHTTPClient(client *http.Client) *CreateVariableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create variable params
func (o *CreateVariableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the create variable params
func (o *CreateVariableParams) WithXWorkspaceID(xWorkspaceID string) *CreateVariableParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the create variable params
func (o *CreateVariableParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithRequest adds the request to the create variable params
func (o *CreateVariableParams) WithRequest(request *models.CreateVariableRequest) *CreateVariableParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create variable params
func (o *CreateVariableParams) SetRequest(request *models.CreateVariableRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVariableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
