// Code generated by go-swagger; DO NOT EDIT.

package variables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// GetVariablesListReader is a Reader for the GetVariablesList structure.
type GetVariablesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVariablesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVariablesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetVariablesListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetVariablesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetVariablesListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVariablesListOK creates a GetVariablesListOK with default headers values
func NewGetVariablesListOK() *GetVariablesListOK {
	return &GetVariablesListOK{}
}

/*
GetVariablesListOK describes a response with status code 200, with default header values.

OK
*/
type GetVariablesListOK struct {

	/* total matching count
	 */
	XTotalCount int64

	Payload []*models.VariableListView
}

func (o *GetVariablesListOK) Error() string {
	return fmt.Sprintf("[GET /admin/variables][%d] getVariablesListOK  %+v", 200, o.Payload)
}
func (o *GetVariablesListOK) GetPayload() []*models.VariableListView {
	return o.Payload
}

func (o *GetVariablesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := swag.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVariablesListBadRequest creates a GetVariablesListBadRequest with default headers values
func NewGetVariablesListBadRequest() *GetVariablesListBadRequest {
	return &GetVariablesListBadRequest{}
}

/*
GetVariablesListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetVariablesListBadRequest struct {
	Payload interface{}
}

func (o *GetVariablesListBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/variables][%d] getVariablesListBadRequest  %+v", 400, o.Payload)
}
func (o *GetVariablesListBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *GetVariablesListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVariablesListNotFound creates a GetVariablesListNotFound with default headers values
func NewGetVariablesListNotFound() *GetVariablesListNotFound {
	return &GetVariablesListNotFound{}
}

/*
GetVariablesListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetVariablesListNotFound struct {
	Payload interface{}
}

func (o *GetVariablesListNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/variables][%d] getVariablesListNotFound  %+v", 404, o.Payload)
}
func (o *GetVariablesListNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *GetVariablesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVariablesListInternalServerError creates a GetVariablesListInternalServerError with default headers values
func NewGetVariablesListInternalServerError() *GetVariablesListInternalServerError {
	return &GetVariablesListInternalServerError{}
}

/*
GetVariablesListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetVariablesListInternalServerError struct {
	Payload interface{}
}

func (o *GetVariablesListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/variables][%d] getVariablesListInternalServerError  %+v", 500, o.Payload)
}
func (o *GetVariablesListInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *GetVariablesListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
