// Code generated by go-swagger; DO NOT EDIT.

package variables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// VariableUpdateReader is a Reader for the VariableUpdate structure.
type VariableUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VariableUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVariableUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVariableUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewVariableUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewVariableUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewVariableUpdateOK creates a VariableUpdateOK with default headers values
func NewVariableUpdateOK() *VariableUpdateOK {
	return &VariableUpdateOK{}
}

/*
VariableUpdateOK describes a response with status code 200, with default header values.

OK
*/
type VariableUpdateOK struct {
	Payload *models.VariableView
}

func (o *VariableUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /admin/variables/{id}][%d] variableUpdateOK  %+v", 200, o.Payload)
}
func (o *VariableUpdateOK) GetPayload() *models.VariableView {
	return o.Payload
}

func (o *VariableUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VariableView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVariableUpdateBadRequest creates a VariableUpdateBadRequest with default headers values
func NewVariableUpdateBadRequest() *VariableUpdateBadRequest {
	return &VariableUpdateBadRequest{}
}

/*
VariableUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VariableUpdateBadRequest struct {
	Payload interface{}
}

func (o *VariableUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /admin/variables/{id}][%d] variableUpdateBadRequest  %+v", 400, o.Payload)
}
func (o *VariableUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *VariableUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVariableUpdateNotFound creates a VariableUpdateNotFound with default headers values
func NewVariableUpdateNotFound() *VariableUpdateNotFound {
	return &VariableUpdateNotFound{}
}

/*
VariableUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type VariableUpdateNotFound struct {
	Payload interface{}
}

func (o *VariableUpdateNotFound) Error() string {
	return fmt.Sprintf("[PUT /admin/variables/{id}][%d] variableUpdateNotFound  %+v", 404, o.Payload)
}
func (o *VariableUpdateNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *VariableUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVariableUpdateInternalServerError creates a VariableUpdateInternalServerError with default headers values
func NewVariableUpdateInternalServerError() *VariableUpdateInternalServerError {
	return &VariableUpdateInternalServerError{}
}

/*
VariableUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type VariableUpdateInternalServerError struct {
	Payload interface{}
}

func (o *VariableUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /admin/variables/{id}][%d] variableUpdateInternalServerError  %+v", 500, o.Payload)
}
func (o *VariableUpdateInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *VariableUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
