// Code generated by go-swagger; DO NOT EDIT.

package variables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVariableGetByIDParams creates a new VariableGetByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVariableGetByIDParams() *VariableGetByIDParams {
	return &VariableGetByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVariableGetByIDParamsWithTimeout creates a new VariableGetByIDParams object
// with the ability to set a timeout on a request.
func NewVariableGetByIDParamsWithTimeout(timeout time.Duration) *VariableGetByIDParams {
	return &VariableGetByIDParams{
		timeout: timeout,
	}
}

// NewVariableGetByIDParamsWithContext creates a new VariableGetByIDParams object
// with the ability to set a context for a request.
func NewVariableGetByIDParamsWithContext(ctx context.Context) *VariableGetByIDParams {
	return &VariableGetByIDParams{
		Context: ctx,
	}
}

// NewVariableGetByIDParamsWithHTTPClient creates a new VariableGetByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewVariableGetByIDParamsWithHTTPClient(client *http.Client) *VariableGetByIDParams {
	return &VariableGetByIDParams{
		HTTPClient: client,
	}
}

/*
VariableGetByIDParams contains all the parameters to send to the API endpoint

	for the variable get by ID operation.

	Typically these are written to a http.Request.
*/
type VariableGetByIDParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* ID.

	   mongo id of the variable
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the variable get by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VariableGetByIDParams) WithDefaults() *VariableGetByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the variable get by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VariableGetByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the variable get by ID params
func (o *VariableGetByIDParams) WithTimeout(timeout time.Duration) *VariableGetByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the variable get by ID params
func (o *VariableGetByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the variable get by ID params
func (o *VariableGetByIDParams) WithContext(ctx context.Context) *VariableGetByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the variable get by ID params
func (o *VariableGetByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the variable get by ID params
func (o *VariableGetByIDParams) WithHTTPClient(client *http.Client) *VariableGetByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the variable get by ID params
func (o *VariableGetByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the variable get by ID params
func (o *VariableGetByIDParams) WithXWorkspaceID(xWorkspaceID string) *VariableGetByIDParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the variable get by ID params
func (o *VariableGetByIDParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithID adds the id to the variable get by ID params
func (o *VariableGetByIDParams) WithID(id string) *VariableGetByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the variable get by ID params
func (o *VariableGetByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *VariableGetByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
