// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// NewApplicationsDeleteTemplateParams creates a new ApplicationsDeleteTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationsDeleteTemplateParams() *ApplicationsDeleteTemplateParams {
	return &ApplicationsDeleteTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationsDeleteTemplateParamsWithTimeout creates a new ApplicationsDeleteTemplateParams object
// with the ability to set a timeout on a request.
func NewApplicationsDeleteTemplateParamsWithTimeout(timeout time.Duration) *ApplicationsDeleteTemplateParams {
	return &ApplicationsDeleteTemplateParams{
		timeout: timeout,
	}
}

// NewApplicationsDeleteTemplateParamsWithContext creates a new ApplicationsDeleteTemplateParams object
// with the ability to set a context for a request.
func NewApplicationsDeleteTemplateParamsWithContext(ctx context.Context) *ApplicationsDeleteTemplateParams {
	return &ApplicationsDeleteTemplateParams{
		Context: ctx,
	}
}

// NewApplicationsDeleteTemplateParamsWithHTTPClient creates a new ApplicationsDeleteTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationsDeleteTemplateParamsWithHTTPClient(client *http.Client) *ApplicationsDeleteTemplateParams {
	return &ApplicationsDeleteTemplateParams{
		HTTPClient: client,
	}
}

/*
ApplicationsDeleteTemplateParams contains all the parameters to send to the API endpoint

	for the applications delete template operation.

	Typically these are written to a http.Request.
*/
type ApplicationsDeleteTemplateParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* Request.

	   req for deleting application from workspace
	*/
	Request *models.DeleteTemplateReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the applications delete template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationsDeleteTemplateParams) WithDefaults() *ApplicationsDeleteTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the applications delete template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationsDeleteTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) WithTimeout(timeout time.Duration) *ApplicationsDeleteTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) WithContext(ctx context.Context) *ApplicationsDeleteTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) WithHTTPClient(client *http.Client) *ApplicationsDeleteTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) WithXWorkspaceID(xWorkspaceID string) *ApplicationsDeleteTemplateParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithRequest adds the request to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) WithRequest(request *models.DeleteTemplateReq) *ApplicationsDeleteTemplateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the applications delete template params
func (o *ApplicationsDeleteTemplateParams) SetRequest(request *models.DeleteTemplateReq) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationsDeleteTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
