// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// NewApplicationCreateTemplateParams creates a new ApplicationCreateTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationCreateTemplateParams() *ApplicationCreateTemplateParams {
	return &ApplicationCreateTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationCreateTemplateParamsWithTimeout creates a new ApplicationCreateTemplateParams object
// with the ability to set a timeout on a request.
func NewApplicationCreateTemplateParamsWithTimeout(timeout time.Duration) *ApplicationCreateTemplateParams {
	return &ApplicationCreateTemplateParams{
		timeout: timeout,
	}
}

// NewApplicationCreateTemplateParamsWithContext creates a new ApplicationCreateTemplateParams object
// with the ability to set a context for a request.
func NewApplicationCreateTemplateParamsWithContext(ctx context.Context) *ApplicationCreateTemplateParams {
	return &ApplicationCreateTemplateParams{
		Context: ctx,
	}
}

// NewApplicationCreateTemplateParamsWithHTTPClient creates a new ApplicationCreateTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationCreateTemplateParamsWithHTTPClient(client *http.Client) *ApplicationCreateTemplateParams {
	return &ApplicationCreateTemplateParams{
		HTTPClient: client,
	}
}

/*
ApplicationCreateTemplateParams contains all the parameters to send to the API endpoint

	for the application create template operation.

	Typically these are written to a http.Request.
*/
type ApplicationCreateTemplateParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* Request.

	   create application template req
	*/
	Request *models.CreateAppTemplateReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application create template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationCreateTemplateParams) WithDefaults() *ApplicationCreateTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application create template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationCreateTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application create template params
func (o *ApplicationCreateTemplateParams) WithTimeout(timeout time.Duration) *ApplicationCreateTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application create template params
func (o *ApplicationCreateTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application create template params
func (o *ApplicationCreateTemplateParams) WithContext(ctx context.Context) *ApplicationCreateTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application create template params
func (o *ApplicationCreateTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application create template params
func (o *ApplicationCreateTemplateParams) WithHTTPClient(client *http.Client) *ApplicationCreateTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application create template params
func (o *ApplicationCreateTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the application create template params
func (o *ApplicationCreateTemplateParams) WithXWorkspaceID(xWorkspaceID string) *ApplicationCreateTemplateParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the application create template params
func (o *ApplicationCreateTemplateParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithRequest adds the request to the application create template params
func (o *ApplicationCreateTemplateParams) WithRequest(request *models.CreateAppTemplateReq) *ApplicationCreateTemplateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the application create template params
func (o *ApplicationCreateTemplateParams) SetRequest(request *models.CreateAppTemplateReq) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationCreateTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
