// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new pipeline API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for pipeline API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
PipelineGetByID get pipeline by id
*/
func (a *Client) PipelineGetByID(params *PipelineGetByIDParams) (*PipelineGetByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPipelineGetByIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "pipelineGetByID",
		Method:             "GET",
		PathPattern:        "/admin/pipeline/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PipelineGetByIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PipelineGetByIDOK), nil

}

/*
PipelineList gives all pipelines
*/
func (a *Client) PipelineList(params *PipelineListParams) (*PipelineListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPipelineListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "pipelineList",
		Method:             "GET",
		PathPattern:        "/admin/pipeline",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PipelineListReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PipelineListOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
