// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWorkspaceGetByIDParams creates a new WorkspaceGetByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWorkspaceGetByIDParams() *WorkspaceGetByIDParams {
	return &WorkspaceGetByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWorkspaceGetByIDParamsWithTimeout creates a new WorkspaceGetByIDParams object
// with the ability to set a timeout on a request.
func NewWorkspaceGetByIDParamsWithTimeout(timeout time.Duration) *WorkspaceGetByIDParams {
	return &WorkspaceGetByIDParams{
		timeout: timeout,
	}
}

// NewWorkspaceGetByIDParamsWithContext creates a new WorkspaceGetByIDParams object
// with the ability to set a context for a request.
func NewWorkspaceGetByIDParamsWithContext(ctx context.Context) *WorkspaceGetByIDParams {
	return &WorkspaceGetByIDParams{
		Context: ctx,
	}
}

// NewWorkspaceGetByIDParamsWithHTTPClient creates a new WorkspaceGetByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewWorkspaceGetByIDParamsWithHTTPClient(client *http.Client) *WorkspaceGetByIDParams {
	return &WorkspaceGetByIDParams{
		HTTPClient: client,
	}
}

/*
WorkspaceGetByIDParams contains all the parameters to send to the API endpoint

	for the workspace get by ID operation.

	Typically these are written to a http.Request.
*/
type WorkspaceGetByIDParams struct {

	/* ID.

	   workspace id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the workspace get by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkspaceGetByIDParams) WithDefaults() *WorkspaceGetByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the workspace get by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkspaceGetByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the workspace get by ID params
func (o *WorkspaceGetByIDParams) WithTimeout(timeout time.Duration) *WorkspaceGetByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the workspace get by ID params
func (o *WorkspaceGetByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the workspace get by ID params
func (o *WorkspaceGetByIDParams) WithContext(ctx context.Context) *WorkspaceGetByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the workspace get by ID params
func (o *WorkspaceGetByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the workspace get by ID params
func (o *WorkspaceGetByIDParams) WithHTTPClient(client *http.Client) *WorkspaceGetByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the workspace get by ID params
func (o *WorkspaceGetByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the workspace get by ID params
func (o *WorkspaceGetByIDParams) WithID(id string) *WorkspaceGetByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the workspace get by ID params
func (o *WorkspaceGetByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *WorkspaceGetByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
