// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// WorkspaceCreateReader is a Reader for the WorkspaceCreate structure.
type WorkspaceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkspaceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkspaceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWorkspaceCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewWorkspaceCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewWorkspaceCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWorkspaceCreateOK creates a WorkspaceCreateOK with default headers values
func NewWorkspaceCreateOK() *WorkspaceCreateOK {
	return &WorkspaceCreateOK{}
}

/*
WorkspaceCreateOK describes a response with status code 200, with default header values.

OK
*/
type WorkspaceCreateOK struct {
	Payload []*models.WorkspaceView
}

func (o *WorkspaceCreateOK) Error() string {
	return fmt.Sprintf("[POST /admin/workspaces][%d] workspaceCreateOK  %+v", 200, o.Payload)
}
func (o *WorkspaceCreateOK) GetPayload() []*models.WorkspaceView {
	return o.Payload
}

func (o *WorkspaceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkspaceCreateBadRequest creates a WorkspaceCreateBadRequest with default headers values
func NewWorkspaceCreateBadRequest() *WorkspaceCreateBadRequest {
	return &WorkspaceCreateBadRequest{}
}

/*
WorkspaceCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type WorkspaceCreateBadRequest struct {
	Payload interface{}
}

func (o *WorkspaceCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /admin/workspaces][%d] workspaceCreateBadRequest  %+v", 400, o.Payload)
}
func (o *WorkspaceCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *WorkspaceCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkspaceCreateNotFound creates a WorkspaceCreateNotFound with default headers values
func NewWorkspaceCreateNotFound() *WorkspaceCreateNotFound {
	return &WorkspaceCreateNotFound{}
}

/*
WorkspaceCreateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type WorkspaceCreateNotFound struct {
	Payload interface{}
}

func (o *WorkspaceCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /admin/workspaces][%d] workspaceCreateNotFound  %+v", 404, o.Payload)
}
func (o *WorkspaceCreateNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *WorkspaceCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkspaceCreateInternalServerError creates a WorkspaceCreateInternalServerError with default headers values
func NewWorkspaceCreateInternalServerError() *WorkspaceCreateInternalServerError {
	return &WorkspaceCreateInternalServerError{}
}

/*
WorkspaceCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type WorkspaceCreateInternalServerError struct {
	Payload interface{}
}

func (o *WorkspaceCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /admin/workspaces][%d] workspaceCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *WorkspaceCreateInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *WorkspaceCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
