// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// WorkspaceListReader is a Reader for the WorkspaceList structure.
type WorkspaceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkspaceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkspaceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWorkspaceListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewWorkspaceListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWorkspaceListOK creates a WorkspaceListOK with default headers values
func NewWorkspaceListOK() *WorkspaceListOK {
	return &WorkspaceListOK{}
}

/*
WorkspaceListOK describes a response with status code 200, with default header values.

OK
*/
type WorkspaceListOK struct {
	Payload []*models.Workspace
}

func (o *WorkspaceListOK) Error() string {
	return fmt.Sprintf("[GET /admin/workspaces][%d] workspaceListOK  %+v", 200, o.Payload)
}
func (o *WorkspaceListOK) GetPayload() []*models.Workspace {
	return o.Payload
}

func (o *WorkspaceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkspaceListBadRequest creates a WorkspaceListBadRequest with default headers values
func NewWorkspaceListBadRequest() *WorkspaceListBadRequest {
	return &WorkspaceListBadRequest{}
}

/*
WorkspaceListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type WorkspaceListBadRequest struct {
	Payload interface{}
}

func (o *WorkspaceListBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/workspaces][%d] workspaceListBadRequest  %+v", 400, o.Payload)
}
func (o *WorkspaceListBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *WorkspaceListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkspaceListInternalServerError creates a WorkspaceListInternalServerError with default headers values
func NewWorkspaceListInternalServerError() *WorkspaceListInternalServerError {
	return &WorkspaceListInternalServerError{}
}

/*
WorkspaceListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type WorkspaceListInternalServerError struct {
	Payload interface{}
}

func (o *WorkspaceListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/workspaces][%d] workspaceListInternalServerError  %+v", 500, o.Payload)
}
func (o *WorkspaceListInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *WorkspaceListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
