// Code generated by go-swagger; DO NOT EDIT.

package pipelinerun

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// PipelineRunCreateReader is a Reader for the PipelineRunCreate structure.
type PipelineRunCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineRunCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPipelineRunCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPipelineRunCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPipelineRunCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPipelineRunCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPipelineRunCreateOK creates a PipelineRunCreateOK with default headers values
func NewPipelineRunCreateOK() *PipelineRunCreateOK {
	return &PipelineRunCreateOK{}
}

/*
PipelineRunCreateOK describes a response with status code 200, with default header values.

OK
*/
type PipelineRunCreateOK struct {
	Payload *models.PipelineRun
}

func (o *PipelineRunCreateOK) Error() string {
	return fmt.Sprintf("[POST /admin/pipelinerun][%d] pipelineRunCreateOK  %+v", 200, o.Payload)
}
func (o *PipelineRunCreateOK) GetPayload() *models.PipelineRun {
	return o.Payload
}

func (o *PipelineRunCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PipelineRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineRunCreateBadRequest creates a PipelineRunCreateBadRequest with default headers values
func NewPipelineRunCreateBadRequest() *PipelineRunCreateBadRequest {
	return &PipelineRunCreateBadRequest{}
}

/*
PipelineRunCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PipelineRunCreateBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *PipelineRunCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /admin/pipelinerun][%d] pipelineRunCreateBadRequest  %+v", 400, o.Payload)
}
func (o *PipelineRunCreateBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PipelineRunCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineRunCreateNotFound creates a PipelineRunCreateNotFound with default headers values
func NewPipelineRunCreateNotFound() *PipelineRunCreateNotFound {
	return &PipelineRunCreateNotFound{}
}

/*
PipelineRunCreateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PipelineRunCreateNotFound struct {
	Payload *models.ErrorMessage
}

func (o *PipelineRunCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /admin/pipelinerun][%d] pipelineRunCreateNotFound  %+v", 404, o.Payload)
}
func (o *PipelineRunCreateNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PipelineRunCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineRunCreateInternalServerError creates a PipelineRunCreateInternalServerError with default headers values
func NewPipelineRunCreateInternalServerError() *PipelineRunCreateInternalServerError {
	return &PipelineRunCreateInternalServerError{}
}

/*
PipelineRunCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PipelineRunCreateInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *PipelineRunCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /admin/pipelinerun][%d] pipelineRunCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *PipelineRunCreateInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PipelineRunCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
