// Code generated by go-swagger; DO NOT EDIT.

package pipelinerun

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// NewPipelineRunCreateParams creates a new PipelineRunCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPipelineRunCreateParams() *PipelineRunCreateParams {
	return &PipelineRunCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPipelineRunCreateParamsWithTimeout creates a new PipelineRunCreateParams object
// with the ability to set a timeout on a request.
func NewPipelineRunCreateParamsWithTimeout(timeout time.Duration) *PipelineRunCreateParams {
	return &PipelineRunCreateParams{
		timeout: timeout,
	}
}

// NewPipelineRunCreateParamsWithContext creates a new PipelineRunCreateParams object
// with the ability to set a context for a request.
func NewPipelineRunCreateParamsWithContext(ctx context.Context) *PipelineRunCreateParams {
	return &PipelineRunCreateParams{
		Context: ctx,
	}
}

// NewPipelineRunCreateParamsWithHTTPClient creates a new PipelineRunCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPipelineRunCreateParamsWithHTTPClient(client *http.Client) *PipelineRunCreateParams {
	return &PipelineRunCreateParams{
		HTTPClient: client,
	}
}

/*
PipelineRunCreateParams contains all the parameters to send to the API endpoint

	for the pipeline run create operation.

	Typically these are written to a http.Request.
*/
type PipelineRunCreateParams struct {

	/* Request.

	   create a pipeline run
	*/
	Request *models.CreatePipelineRunRequest

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pipeline run create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineRunCreateParams) WithDefaults() *PipelineRunCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pipeline run create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineRunCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pipeline run create params
func (o *PipelineRunCreateParams) WithTimeout(timeout time.Duration) *PipelineRunCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline run create params
func (o *PipelineRunCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pipeline run create params
func (o *PipelineRunCreateParams) WithContext(ctx context.Context) *PipelineRunCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline run create params
func (o *PipelineRunCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline run create params
func (o *PipelineRunCreateParams) WithHTTPClient(client *http.Client) *PipelineRunCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline run create params
func (o *PipelineRunCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the pipeline run create params
func (o *PipelineRunCreateParams) WithRequest(request *models.CreatePipelineRunRequest) *PipelineRunCreateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the pipeline run create params
func (o *PipelineRunCreateParams) SetRequest(request *models.CreatePipelineRunRequest) {
	o.Request = request
}

// WithXWorkspaceID adds the xWorkspaceID to the pipeline run create params
func (o *PipelineRunCreateParams) WithXWorkspaceID(xWorkspaceID string) *PipelineRunCreateParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the pipeline run create params
func (o *PipelineRunCreateParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *PipelineRunCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param x-workspace-id
	if err := r.SetHeaderParam("x-workspace-id", o.XWorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
