// Code generated by go-swagger; DO NOT EDIT.

package pipelinerun

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPipelineRunGetByIDParams creates a new PipelineRunGetByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPipelineRunGetByIDParams() *PipelineRunGetByIDParams {
	return &PipelineRunGetByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPipelineRunGetByIDParamsWithTimeout creates a new PipelineRunGetByIDParams object
// with the ability to set a timeout on a request.
func NewPipelineRunGetByIDParamsWithTimeout(timeout time.Duration) *PipelineRunGetByIDParams {
	return &PipelineRunGetByIDParams{
		timeout: timeout,
	}
}

// NewPipelineRunGetByIDParamsWithContext creates a new PipelineRunGetByIDParams object
// with the ability to set a context for a request.
func NewPipelineRunGetByIDParamsWithContext(ctx context.Context) *PipelineRunGetByIDParams {
	return &PipelineRunGetByIDParams{
		Context: ctx,
	}
}

// NewPipelineRunGetByIDParamsWithHTTPClient creates a new PipelineRunGetByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPipelineRunGetByIDParamsWithHTTPClient(client *http.Client) *PipelineRunGetByIDParams {
	return &PipelineRunGetByIDParams{
		HTTPClient: client,
	}
}

/*
PipelineRunGetByIDParams contains all the parameters to send to the API endpoint

	for the pipeline run get by ID operation.

	Typically these are written to a http.Request.
*/
type PipelineRunGetByIDParams struct {

	/* ID.

	   id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pipeline run get by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineRunGetByIDParams) WithDefaults() *PipelineRunGetByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pipeline run get by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineRunGetByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) WithTimeout(timeout time.Duration) *PipelineRunGetByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) WithContext(ctx context.Context) *PipelineRunGetByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) WithHTTPClient(client *http.Client) *PipelineRunGetByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) WithID(id string) *PipelineRunGetByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pipeline run get by ID params
func (o *PipelineRunGetByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PipelineRunGetByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
