// Code generated by go-swagger; DO NOT EDIT.

package pipelinerun

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPipelineRunGetParams creates a new PipelineRunGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPipelineRunGetParams() *PipelineRunGetParams {
	return &PipelineRunGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPipelineRunGetParamsWithTimeout creates a new PipelineRunGetParams object
// with the ability to set a timeout on a request.
func NewPipelineRunGetParamsWithTimeout(timeout time.Duration) *PipelineRunGetParams {
	return &PipelineRunGetParams{
		timeout: timeout,
	}
}

// NewPipelineRunGetParamsWithContext creates a new PipelineRunGetParams object
// with the ability to set a context for a request.
func NewPipelineRunGetParamsWithContext(ctx context.Context) *PipelineRunGetParams {
	return &PipelineRunGetParams{
		Context: ctx,
	}
}

// NewPipelineRunGetParamsWithHTTPClient creates a new PipelineRunGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewPipelineRunGetParamsWithHTTPClient(client *http.Client) *PipelineRunGetParams {
	return &PipelineRunGetParams{
		HTTPClient: client,
	}
}

/*
PipelineRunGetParams contains all the parameters to send to the API endpoint

	for the pipeline run get operation.

	Typically these are written to a http.Request.
*/
type PipelineRunGetParams struct {

	/* End.

	   end
	*/
	End *int64

	/* Order.

	   sort order
	*/
	Order *string

	/* Sort.

	   sort column
	*/
	Sort *string

	/* Start.

	   start
	*/
	Start *int64

	/* ApplicationID.

	   applicationID
	*/
	ApplicationID *string

	/* MicroserviceSlug.

	   microserviceSlug
	*/
	MicroserviceSlug *string

	/* Q.

	   filter by name
	*/
	Q *string

	/* RegistryID.

	   filter by registry_id
	*/
	RegistryID *string

	/* RepositoryID.

	   filter by repository_id
	*/
	RepositoryID *string

	/* Type.

	   filter by type
	*/
	Type *string

	/* XWorkspaceID.

	   X-Workspace-ID
	*/
	XWorkspaceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pipeline run get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineRunGetParams) WithDefaults() *PipelineRunGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pipeline run get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineRunGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pipeline run get params
func (o *PipelineRunGetParams) WithTimeout(timeout time.Duration) *PipelineRunGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline run get params
func (o *PipelineRunGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pipeline run get params
func (o *PipelineRunGetParams) WithContext(ctx context.Context) *PipelineRunGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline run get params
func (o *PipelineRunGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline run get params
func (o *PipelineRunGetParams) WithHTTPClient(client *http.Client) *PipelineRunGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline run get params
func (o *PipelineRunGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the pipeline run get params
func (o *PipelineRunGetParams) WithEnd(end *int64) *PipelineRunGetParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the pipeline run get params
func (o *PipelineRunGetParams) SetEnd(end *int64) {
	o.End = end
}

// WithOrder adds the order to the pipeline run get params
func (o *PipelineRunGetParams) WithOrder(order *string) *PipelineRunGetParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the pipeline run get params
func (o *PipelineRunGetParams) SetOrder(order *string) {
	o.Order = order
}

// WithSort adds the sort to the pipeline run get params
func (o *PipelineRunGetParams) WithSort(sort *string) *PipelineRunGetParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the pipeline run get params
func (o *PipelineRunGetParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithStart adds the start to the pipeline run get params
func (o *PipelineRunGetParams) WithStart(start *int64) *PipelineRunGetParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the pipeline run get params
func (o *PipelineRunGetParams) SetStart(start *int64) {
	o.Start = start
}

// WithApplicationID adds the applicationID to the pipeline run get params
func (o *PipelineRunGetParams) WithApplicationID(applicationID *string) *PipelineRunGetParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the pipeline run get params
func (o *PipelineRunGetParams) SetApplicationID(applicationID *string) {
	o.ApplicationID = applicationID
}

// WithMicroserviceSlug adds the microserviceSlug to the pipeline run get params
func (o *PipelineRunGetParams) WithMicroserviceSlug(microserviceSlug *string) *PipelineRunGetParams {
	o.SetMicroserviceSlug(microserviceSlug)
	return o
}

// SetMicroserviceSlug adds the microserviceSlug to the pipeline run get params
func (o *PipelineRunGetParams) SetMicroserviceSlug(microserviceSlug *string) {
	o.MicroserviceSlug = microserviceSlug
}

// WithQ adds the q to the pipeline run get params
func (o *PipelineRunGetParams) WithQ(q *string) *PipelineRunGetParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the pipeline run get params
func (o *PipelineRunGetParams) SetQ(q *string) {
	o.Q = q
}

// WithRegistryID adds the registryID to the pipeline run get params
func (o *PipelineRunGetParams) WithRegistryID(registryID *string) *PipelineRunGetParams {
	o.SetRegistryID(registryID)
	return o
}

// SetRegistryID adds the registryId to the pipeline run get params
func (o *PipelineRunGetParams) SetRegistryID(registryID *string) {
	o.RegistryID = registryID
}

// WithRepositoryID adds the repositoryID to the pipeline run get params
func (o *PipelineRunGetParams) WithRepositoryID(repositoryID *string) *PipelineRunGetParams {
	o.SetRepositoryID(repositoryID)
	return o
}

// SetRepositoryID adds the repositoryId to the pipeline run get params
func (o *PipelineRunGetParams) SetRepositoryID(repositoryID *string) {
	o.RepositoryID = repositoryID
}

// WithType adds the typeVar to the pipeline run get params
func (o *PipelineRunGetParams) WithType(typeVar *string) *PipelineRunGetParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the pipeline run get params
func (o *PipelineRunGetParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithXWorkspaceID adds the xWorkspaceID to the pipeline run get params
func (o *PipelineRunGetParams) WithXWorkspaceID(xWorkspaceID *string) *PipelineRunGetParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the pipeline run get params
func (o *PipelineRunGetParams) SetXWorkspaceID(xWorkspaceID *string) {
	o.XWorkspaceID = xWorkspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *PipelineRunGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.End != nil {

		// query param _end
		var qrEnd int64

		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := swag.FormatInt64(qrEnd)
		if qEnd != "" {

			if err := r.SetQueryParam("_end", qEnd); err != nil {
				return err
			}
		}
	}

	if o.Order != nil {

		// query param _order
		var qrOrder string

		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {

			if err := r.SetQueryParam("_order", qOrder); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param _sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("_sort", qSort); err != nil {
				return err
			}
		}
	}

	if o.Start != nil {

		// query param _start
		var qrStart int64

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt64(qrStart)
		if qStart != "" {

			if err := r.SetQueryParam("_start", qStart); err != nil {
				return err
			}
		}
	}

	if o.ApplicationID != nil {

		// query param applicationID
		var qrApplicationID string

		if o.ApplicationID != nil {
			qrApplicationID = *o.ApplicationID
		}
		qApplicationID := qrApplicationID
		if qApplicationID != "" {

			if err := r.SetQueryParam("applicationID", qApplicationID); err != nil {
				return err
			}
		}
	}

	if o.MicroserviceSlug != nil {

		// query param microserviceSlug
		var qrMicroserviceSlug string

		if o.MicroserviceSlug != nil {
			qrMicroserviceSlug = *o.MicroserviceSlug
		}
		qMicroserviceSlug := qrMicroserviceSlug
		if qMicroserviceSlug != "" {

			if err := r.SetQueryParam("microserviceSlug", qMicroserviceSlug); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.RegistryID != nil {

		// query param registry_id
		var qrRegistryID string

		if o.RegistryID != nil {
			qrRegistryID = *o.RegistryID
		}
		qRegistryID := qrRegistryID
		if qRegistryID != "" {

			if err := r.SetQueryParam("registry_id", qRegistryID); err != nil {
				return err
			}
		}
	}

	if o.RepositoryID != nil {

		// query param repository_id
		var qrRepositoryID string

		if o.RepositoryID != nil {
			qrRepositoryID = *o.RepositoryID
		}
		qRepositoryID := qrRepositoryID
		if qRepositoryID != "" {

			if err := r.SetQueryParam("repository_id", qRepositoryID); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if o.XWorkspaceID != nil {

		// header param x-workspace-id
		if err := r.SetHeaderParam("x-workspace-id", *o.XWorkspaceID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
