// Code generated by go-swagger; DO NOT EDIT.

package releaserun

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListReleaseRunsParams creates a new ListReleaseRunsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListReleaseRunsParams() *ListReleaseRunsParams {
	return &ListReleaseRunsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListReleaseRunsParamsWithTimeout creates a new ListReleaseRunsParams object
// with the ability to set a timeout on a request.
func NewListReleaseRunsParamsWithTimeout(timeout time.Duration) *ListReleaseRunsParams {
	return &ListReleaseRunsParams{
		timeout: timeout,
	}
}

// NewListReleaseRunsParamsWithContext creates a new ListReleaseRunsParams object
// with the ability to set a context for a request.
func NewListReleaseRunsParamsWithContext(ctx context.Context) *ListReleaseRunsParams {
	return &ListReleaseRunsParams{
		Context: ctx,
	}
}

// NewListReleaseRunsParamsWithHTTPClient creates a new ListReleaseRunsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListReleaseRunsParamsWithHTTPClient(client *http.Client) *ListReleaseRunsParams {
	return &ListReleaseRunsParams{
		HTTPClient: client,
	}
}

/*
ListReleaseRunsParams contains all the parameters to send to the API endpoint

	for the list release runs operation.

	Typically these are written to a http.Request.
*/
type ListReleaseRunsParams struct {

	/* End.

	   end
	*/
	End *int64

	/* Order.

	   sort order
	*/
	Order *string

	/* Sort.

	   sort column
	*/
	Sort *string

	/* Start.

	   start
	*/
	Start *int64

	/* Q.

	   filter by name
	*/
	Q *string

	/* RegistryID.

	   filter by registry_id
	*/
	RegistryID *string

	/* RepositoryID.

	   filter by repository_id
	*/
	RepositoryID *string

	/* Type.

	   filter by type
	*/
	Type *string

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list release runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListReleaseRunsParams) WithDefaults() *ListReleaseRunsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list release runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListReleaseRunsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list release runs params
func (o *ListReleaseRunsParams) WithTimeout(timeout time.Duration) *ListReleaseRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list release runs params
func (o *ListReleaseRunsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list release runs params
func (o *ListReleaseRunsParams) WithContext(ctx context.Context) *ListReleaseRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list release runs params
func (o *ListReleaseRunsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list release runs params
func (o *ListReleaseRunsParams) WithHTTPClient(client *http.Client) *ListReleaseRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list release runs params
func (o *ListReleaseRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the list release runs params
func (o *ListReleaseRunsParams) WithEnd(end *int64) *ListReleaseRunsParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the list release runs params
func (o *ListReleaseRunsParams) SetEnd(end *int64) {
	o.End = end
}

// WithOrder adds the order to the list release runs params
func (o *ListReleaseRunsParams) WithOrder(order *string) *ListReleaseRunsParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the list release runs params
func (o *ListReleaseRunsParams) SetOrder(order *string) {
	o.Order = order
}

// WithSort adds the sort to the list release runs params
func (o *ListReleaseRunsParams) WithSort(sort *string) *ListReleaseRunsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the list release runs params
func (o *ListReleaseRunsParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithStart adds the start to the list release runs params
func (o *ListReleaseRunsParams) WithStart(start *int64) *ListReleaseRunsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the list release runs params
func (o *ListReleaseRunsParams) SetStart(start *int64) {
	o.Start = start
}

// WithQ adds the q to the list release runs params
func (o *ListReleaseRunsParams) WithQ(q *string) *ListReleaseRunsParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the list release runs params
func (o *ListReleaseRunsParams) SetQ(q *string) {
	o.Q = q
}

// WithRegistryID adds the registryID to the list release runs params
func (o *ListReleaseRunsParams) WithRegistryID(registryID *string) *ListReleaseRunsParams {
	o.SetRegistryID(registryID)
	return o
}

// SetRegistryID adds the registryId to the list release runs params
func (o *ListReleaseRunsParams) SetRegistryID(registryID *string) {
	o.RegistryID = registryID
}

// WithRepositoryID adds the repositoryID to the list release runs params
func (o *ListReleaseRunsParams) WithRepositoryID(repositoryID *string) *ListReleaseRunsParams {
	o.SetRepositoryID(repositoryID)
	return o
}

// SetRepositoryID adds the repositoryId to the list release runs params
func (o *ListReleaseRunsParams) SetRepositoryID(repositoryID *string) {
	o.RepositoryID = repositoryID
}

// WithType adds the typeVar to the list release runs params
func (o *ListReleaseRunsParams) WithType(typeVar *string) *ListReleaseRunsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the list release runs params
func (o *ListReleaseRunsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithXWorkspaceID adds the xWorkspaceID to the list release runs params
func (o *ListReleaseRunsParams) WithXWorkspaceID(xWorkspaceID string) *ListReleaseRunsParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the list release runs params
func (o *ListReleaseRunsParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *ListReleaseRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.End != nil {

		// query param _end
		var qrEnd int64

		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := swag.FormatInt64(qrEnd)
		if qEnd != "" {

			if err := r.SetQueryParam("_end", qEnd); err != nil {
				return err
			}
		}
	}

	if o.Order != nil {

		// query param _order
		var qrOrder string

		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {

			if err := r.SetQueryParam("_order", qOrder); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param _sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("_sort", qSort); err != nil {
				return err
			}
		}
	}

	if o.Start != nil {

		// query param _start
		var qrStart int64

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt64(qrStart)
		if qStart != "" {

			if err := r.SetQueryParam("_start", qStart); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.RegistryID != nil {

		// query param registry_id
		var qrRegistryID string

		if o.RegistryID != nil {
			qrRegistryID = *o.RegistryID
		}
		qRegistryID := qrRegistryID
		if qRegistryID != "" {

			if err := r.SetQueryParam("registry_id", qRegistryID); err != nil {
				return err
			}
		}
	}

	if o.RepositoryID != nil {

		// query param repository_id
		var qrRepositoryID string

		if o.RepositoryID != nil {
			qrRepositoryID = *o.RepositoryID
		}
		qRepositoryID := qrRepositoryID
		if qRepositoryID != "" {

			if err := r.SetQueryParam("repository_id", qRepositoryID); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	// header param x-workspace-id
	if err := r.SetHeaderParam("x-workspace-id", o.XWorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
