// Code generated by go-swagger; DO NOT EDIT.

package releaserun

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ListReleaseRunsReader is a Reader for the ListReleaseRuns structure.
type ListReleaseRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListReleaseRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListReleaseRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListReleaseRunsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListReleaseRunsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListReleaseRunsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListReleaseRunsOK creates a ListReleaseRunsOK with default headers values
func NewListReleaseRunsOK() *ListReleaseRunsOK {
	return &ListReleaseRunsOK{}
}

/*
ListReleaseRunsOK describes a response with status code 200, with default header values.

OK
*/
type ListReleaseRunsOK struct {

	/* total matching count
	 */
	XTotalCount int64

	Payload *models.ReleaseRunList
}

func (o *ListReleaseRunsOK) Error() string {
	return fmt.Sprintf("[GET /admin/releaserun][%d] listReleaseRunsOK  %+v", 200, o.Payload)
}
func (o *ListReleaseRunsOK) GetPayload() *models.ReleaseRunList {
	return o.Payload
}

func (o *ListReleaseRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := swag.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	o.Payload = new(models.ReleaseRunList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListReleaseRunsBadRequest creates a ListReleaseRunsBadRequest with default headers values
func NewListReleaseRunsBadRequest() *ListReleaseRunsBadRequest {
	return &ListReleaseRunsBadRequest{}
}

/*
ListReleaseRunsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListReleaseRunsBadRequest struct {
	Payload interface{}
}

func (o *ListReleaseRunsBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/releaserun][%d] listReleaseRunsBadRequest  %+v", 400, o.Payload)
}
func (o *ListReleaseRunsBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ListReleaseRunsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListReleaseRunsNotFound creates a ListReleaseRunsNotFound with default headers values
func NewListReleaseRunsNotFound() *ListReleaseRunsNotFound {
	return &ListReleaseRunsNotFound{}
}

/*
ListReleaseRunsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListReleaseRunsNotFound struct {
	Payload interface{}
}

func (o *ListReleaseRunsNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/releaserun][%d] listReleaseRunsNotFound  %+v", 404, o.Payload)
}
func (o *ListReleaseRunsNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ListReleaseRunsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListReleaseRunsInternalServerError creates a ListReleaseRunsInternalServerError with default headers values
func NewListReleaseRunsInternalServerError() *ListReleaseRunsInternalServerError {
	return &ListReleaseRunsInternalServerError{}
}

/*
ListReleaseRunsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListReleaseRunsInternalServerError struct {
	Payload interface{}
}

func (o *ListReleaseRunsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/releaserun][%d] listReleaseRunsInternalServerError  %+v", 500, o.Payload)
}
func (o *ListReleaseRunsInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ListReleaseRunsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
