// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ListReleaseStepTypesReader is a Reader for the ListReleaseStepTypes structure.
type ListReleaseStepTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListReleaseStepTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListReleaseStepTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListReleaseStepTypesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListReleaseStepTypesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListReleaseStepTypesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListReleaseStepTypesOK creates a ListReleaseStepTypesOK with default headers values
func NewListReleaseStepTypesOK() *ListReleaseStepTypesOK {
	return &ListReleaseStepTypesOK{}
}

/*
ListReleaseStepTypesOK describes a response with status code 200, with default header values.

OK
*/
type ListReleaseStepTypesOK struct {

	/* total matching count
	 */
	XTotalCount int64

	Payload []*models.ReleaseStepType
}

func (o *ListReleaseStepTypesOK) Error() string {
	return fmt.Sprintf("[GET /admin/releasesteptypes][%d] listReleaseStepTypesOK  %+v", 200, o.Payload)
}
func (o *ListReleaseStepTypesOK) GetPayload() []*models.ReleaseStepType {
	return o.Payload
}

func (o *ListReleaseStepTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := swag.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListReleaseStepTypesBadRequest creates a ListReleaseStepTypesBadRequest with default headers values
func NewListReleaseStepTypesBadRequest() *ListReleaseStepTypesBadRequest {
	return &ListReleaseStepTypesBadRequest{}
}

/*
ListReleaseStepTypesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListReleaseStepTypesBadRequest struct {
	Payload interface{}
}

func (o *ListReleaseStepTypesBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/releasesteptypes][%d] listReleaseStepTypesBadRequest  %+v", 400, o.Payload)
}
func (o *ListReleaseStepTypesBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ListReleaseStepTypesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListReleaseStepTypesNotFound creates a ListReleaseStepTypesNotFound with default headers values
func NewListReleaseStepTypesNotFound() *ListReleaseStepTypesNotFound {
	return &ListReleaseStepTypesNotFound{}
}

/*
ListReleaseStepTypesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListReleaseStepTypesNotFound struct {
	Payload interface{}
}

func (o *ListReleaseStepTypesNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/releasesteptypes][%d] listReleaseStepTypesNotFound  %+v", 404, o.Payload)
}
func (o *ListReleaseStepTypesNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ListReleaseStepTypesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListReleaseStepTypesInternalServerError creates a ListReleaseStepTypesInternalServerError with default headers values
func NewListReleaseStepTypesInternalServerError() *ListReleaseStepTypesInternalServerError {
	return &ListReleaseStepTypesInternalServerError{}
}

/*
ListReleaseStepTypesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListReleaseStepTypesInternalServerError struct {
	Payload interface{}
}

func (o *ListReleaseStepTypesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/releasesteptypes][%d] listReleaseStepTypesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListReleaseStepTypesInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ListReleaseStepTypesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
