// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListReleaseStepTypesParams creates a new ListReleaseStepTypesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListReleaseStepTypesParams() *ListReleaseStepTypesParams {
	return &ListReleaseStepTypesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListReleaseStepTypesParamsWithTimeout creates a new ListReleaseStepTypesParams object
// with the ability to set a timeout on a request.
func NewListReleaseStepTypesParamsWithTimeout(timeout time.Duration) *ListReleaseStepTypesParams {
	return &ListReleaseStepTypesParams{
		timeout: timeout,
	}
}

// NewListReleaseStepTypesParamsWithContext creates a new ListReleaseStepTypesParams object
// with the ability to set a context for a request.
func NewListReleaseStepTypesParamsWithContext(ctx context.Context) *ListReleaseStepTypesParams {
	return &ListReleaseStepTypesParams{
		Context: ctx,
	}
}

// NewListReleaseStepTypesParamsWithHTTPClient creates a new ListReleaseStepTypesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListReleaseStepTypesParamsWithHTTPClient(client *http.Client) *ListReleaseStepTypesParams {
	return &ListReleaseStepTypesParams{
		HTTPClient: client,
	}
}

/*
ListReleaseStepTypesParams contains all the parameters to send to the API endpoint

	for the list release step types operation.

	Typically these are written to a http.Request.
*/
type ListReleaseStepTypesParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list release step types params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListReleaseStepTypesParams) WithDefaults() *ListReleaseStepTypesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list release step types params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListReleaseStepTypesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list release step types params
func (o *ListReleaseStepTypesParams) WithTimeout(timeout time.Duration) *ListReleaseStepTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list release step types params
func (o *ListReleaseStepTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list release step types params
func (o *ListReleaseStepTypesParams) WithContext(ctx context.Context) *ListReleaseStepTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list release step types params
func (o *ListReleaseStepTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list release step types params
func (o *ListReleaseStepTypesParams) WithHTTPClient(client *http.Client) *ListReleaseStepTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list release step types params
func (o *ListReleaseStepTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the list release step types params
func (o *ListReleaseStepTypesParams) WithXWorkspaceID(xWorkspaceID string) *ListReleaseStepTypesParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the list release step types params
func (o *ListReleaseStepTypesParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *ListReleaseStepTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
