// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// NewApplicationsUpdateParams creates a new ApplicationsUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationsUpdateParams() *ApplicationsUpdateParams {
	return &ApplicationsUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationsUpdateParamsWithTimeout creates a new ApplicationsUpdateParams object
// with the ability to set a timeout on a request.
func NewApplicationsUpdateParamsWithTimeout(timeout time.Duration) *ApplicationsUpdateParams {
	return &ApplicationsUpdateParams{
		timeout: timeout,
	}
}

// NewApplicationsUpdateParamsWithContext creates a new ApplicationsUpdateParams object
// with the ability to set a context for a request.
func NewApplicationsUpdateParamsWithContext(ctx context.Context) *ApplicationsUpdateParams {
	return &ApplicationsUpdateParams{
		Context: ctx,
	}
}

// NewApplicationsUpdateParamsWithHTTPClient creates a new ApplicationsUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationsUpdateParamsWithHTTPClient(client *http.Client) *ApplicationsUpdateParams {
	return &ApplicationsUpdateParams{
		HTTPClient: client,
	}
}

/*
ApplicationsUpdateParams contains all the parameters to send to the API endpoint

	for the applications update operation.

	Typically these are written to a http.Request.
*/
type ApplicationsUpdateParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* ID.

	   mongo id of the application
	*/
	ID string

	/* Request.

	   update application request
	*/
	Request *models.CreateApplicationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the applications update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationsUpdateParams) WithDefaults() *ApplicationsUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the applications update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationsUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the applications update params
func (o *ApplicationsUpdateParams) WithTimeout(timeout time.Duration) *ApplicationsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the applications update params
func (o *ApplicationsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the applications update params
func (o *ApplicationsUpdateParams) WithContext(ctx context.Context) *ApplicationsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the applications update params
func (o *ApplicationsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the applications update params
func (o *ApplicationsUpdateParams) WithHTTPClient(client *http.Client) *ApplicationsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the applications update params
func (o *ApplicationsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the applications update params
func (o *ApplicationsUpdateParams) WithXWorkspaceID(xWorkspaceID string) *ApplicationsUpdateParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the applications update params
func (o *ApplicationsUpdateParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithID adds the id to the applications update params
func (o *ApplicationsUpdateParams) WithID(id string) *ApplicationsUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the applications update params
func (o *ApplicationsUpdateParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the applications update params
func (o *ApplicationsUpdateParams) WithRequest(request *models.CreateApplicationRequest) *ApplicationsUpdateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the applications update params
func (o *ApplicationsUpdateParams) SetRequest(request *models.CreateApplicationRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
