// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ApplicationGetByIDReader is a Reader for the ApplicationGetByID structure.
type ApplicationGetByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationGetByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationGetByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewApplicationGetByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewApplicationGetByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewApplicationGetByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewApplicationGetByIDOK creates a ApplicationGetByIDOK with default headers values
func NewApplicationGetByIDOK() *ApplicationGetByIDOK {
	return &ApplicationGetByIDOK{}
}

/*
ApplicationGetByIDOK describes a response with status code 200, with default header values.

OK
*/
type ApplicationGetByIDOK struct {
	Payload *models.Application
}

func (o *ApplicationGetByIDOK) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}][%d] applicationGetByIdOK  %+v", 200, o.Payload)
}
func (o *ApplicationGetByIDOK) GetPayload() *models.Application {
	return o.Payload
}

func (o *ApplicationGetByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationGetByIDBadRequest creates a ApplicationGetByIDBadRequest with default headers values
func NewApplicationGetByIDBadRequest() *ApplicationGetByIDBadRequest {
	return &ApplicationGetByIDBadRequest{}
}

/*
ApplicationGetByIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ApplicationGetByIDBadRequest struct {
	Payload interface{}
}

func (o *ApplicationGetByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}][%d] applicationGetByIdBadRequest  %+v", 400, o.Payload)
}
func (o *ApplicationGetByIDBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationGetByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationGetByIDNotFound creates a ApplicationGetByIDNotFound with default headers values
func NewApplicationGetByIDNotFound() *ApplicationGetByIDNotFound {
	return &ApplicationGetByIDNotFound{}
}

/*
ApplicationGetByIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ApplicationGetByIDNotFound struct {
	Payload interface{}
}

func (o *ApplicationGetByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}][%d] applicationGetByIdNotFound  %+v", 404, o.Payload)
}
func (o *ApplicationGetByIDNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationGetByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationGetByIDInternalServerError creates a ApplicationGetByIDInternalServerError with default headers values
func NewApplicationGetByIDInternalServerError() *ApplicationGetByIDInternalServerError {
	return &ApplicationGetByIDInternalServerError{}
}

/*
ApplicationGetByIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ApplicationGetByIDInternalServerError struct {
	Payload interface{}
}

func (o *ApplicationGetByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}][%d] applicationGetByIdInternalServerError  %+v", 500, o.Payload)
}
func (o *ApplicationGetByIDInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationGetByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
