// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ApplicationsUpdateReader is a Reader for the ApplicationsUpdate structure.
type ApplicationsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewApplicationsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewApplicationsUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewApplicationsUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewApplicationsUpdateOK creates a ApplicationsUpdateOK with default headers values
func NewApplicationsUpdateOK() *ApplicationsUpdateOK {
	return &ApplicationsUpdateOK{}
}

/*
ApplicationsUpdateOK describes a response with status code 200, with default header values.

OK
*/
type ApplicationsUpdateOK struct {
	Payload *models.Application
}

func (o *ApplicationsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /admin/app/{id}][%d] applicationsUpdateOK  %+v", 200, o.Payload)
}
func (o *ApplicationsUpdateOK) GetPayload() *models.Application {
	return o.Payload
}

func (o *ApplicationsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationsUpdateBadRequest creates a ApplicationsUpdateBadRequest with default headers values
func NewApplicationsUpdateBadRequest() *ApplicationsUpdateBadRequest {
	return &ApplicationsUpdateBadRequest{}
}

/*
ApplicationsUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ApplicationsUpdateBadRequest struct {
	Payload interface{}
}

func (o *ApplicationsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /admin/app/{id}][%d] applicationsUpdateBadRequest  %+v", 400, o.Payload)
}
func (o *ApplicationsUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationsUpdateNotFound creates a ApplicationsUpdateNotFound with default headers values
func NewApplicationsUpdateNotFound() *ApplicationsUpdateNotFound {
	return &ApplicationsUpdateNotFound{}
}

/*
ApplicationsUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ApplicationsUpdateNotFound struct {
	Payload interface{}
}

func (o *ApplicationsUpdateNotFound) Error() string {
	return fmt.Sprintf("[PUT /admin/app/{id}][%d] applicationsUpdateNotFound  %+v", 404, o.Payload)
}
func (o *ApplicationsUpdateNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationsUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationsUpdateInternalServerError creates a ApplicationsUpdateInternalServerError with default headers values
func NewApplicationsUpdateInternalServerError() *ApplicationsUpdateInternalServerError {
	return &ApplicationsUpdateInternalServerError{}
}

/*
ApplicationsUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ApplicationsUpdateInternalServerError struct {
	Payload interface{}
}

func (o *ApplicationsUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /admin/app/{id}][%d] applicationsUpdateInternalServerError  %+v", 500, o.Payload)
}
func (o *ApplicationsUpdateInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationsUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
