// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ApplicationCreateReader is a Reader for the ApplicationCreate structure.
type ApplicationCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewApplicationCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewApplicationCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewApplicationCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewApplicationCreateOK creates a ApplicationCreateOK with default headers values
func NewApplicationCreateOK() *ApplicationCreateOK {
	return &ApplicationCreateOK{}
}

/*
ApplicationCreateOK describes a response with status code 200, with default header values.

OK
*/
type ApplicationCreateOK struct {
	Payload *models.GithubComOzoneCloudCommonEntitiesApplicationApplication
}

func (o *ApplicationCreateOK) Error() string {
	return fmt.Sprintf("[POST /admin/app][%d] applicationCreateOK  %+v", 200, o.Payload)
}
func (o *ApplicationCreateOK) GetPayload() *models.GithubComOzoneCloudCommonEntitiesApplicationApplication {
	return o.Payload
}

func (o *ApplicationCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComOzoneCloudCommonEntitiesApplicationApplication)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationCreateBadRequest creates a ApplicationCreateBadRequest with default headers values
func NewApplicationCreateBadRequest() *ApplicationCreateBadRequest {
	return &ApplicationCreateBadRequest{}
}

/*
ApplicationCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ApplicationCreateBadRequest struct {
	Payload interface{}
}

func (o *ApplicationCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /admin/app][%d] applicationCreateBadRequest  %+v", 400, o.Payload)
}
func (o *ApplicationCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationCreateNotFound creates a ApplicationCreateNotFound with default headers values
func NewApplicationCreateNotFound() *ApplicationCreateNotFound {
	return &ApplicationCreateNotFound{}
}

/*
ApplicationCreateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ApplicationCreateNotFound struct {
	Payload interface{}
}

func (o *ApplicationCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /admin/app][%d] applicationCreateNotFound  %+v", 404, o.Payload)
}
func (o *ApplicationCreateNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationCreateInternalServerError creates a ApplicationCreateInternalServerError with default headers values
func NewApplicationCreateInternalServerError() *ApplicationCreateInternalServerError {
	return &ApplicationCreateInternalServerError{}
}

/*
ApplicationCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ApplicationCreateInternalServerError struct {
	Payload interface{}
}

func (o *ApplicationCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /admin/app][%d] applicationCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *ApplicationCreateInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ApplicationCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
