// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListApplicationReleasesParams creates a new ListApplicationReleasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListApplicationReleasesParams() *ListApplicationReleasesParams {
	return &ListApplicationReleasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListApplicationReleasesParamsWithTimeout creates a new ListApplicationReleasesParams object
// with the ability to set a timeout on a request.
func NewListApplicationReleasesParamsWithTimeout(timeout time.Duration) *ListApplicationReleasesParams {
	return &ListApplicationReleasesParams{
		timeout: timeout,
	}
}

// NewListApplicationReleasesParamsWithContext creates a new ListApplicationReleasesParams object
// with the ability to set a context for a request.
func NewListApplicationReleasesParamsWithContext(ctx context.Context) *ListApplicationReleasesParams {
	return &ListApplicationReleasesParams{
		Context: ctx,
	}
}

// NewListApplicationReleasesParamsWithHTTPClient creates a new ListApplicationReleasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListApplicationReleasesParamsWithHTTPClient(client *http.Client) *ListApplicationReleasesParams {
	return &ListApplicationReleasesParams{
		HTTPClient: client,
	}
}

/*
ListApplicationReleasesParams contains all the parameters to send to the API endpoint

	for the list application releases operation.

	Typically these are written to a http.Request.
*/
type ListApplicationReleasesParams struct {

	/* XWorkspaceID.

	   workspace id
	*/
	XWorkspaceID string

	/* ID.

	   mongo id of the application
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list application releases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListApplicationReleasesParams) WithDefaults() *ListApplicationReleasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list application releases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListApplicationReleasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list application releases params
func (o *ListApplicationReleasesParams) WithTimeout(timeout time.Duration) *ListApplicationReleasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list application releases params
func (o *ListApplicationReleasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list application releases params
func (o *ListApplicationReleasesParams) WithContext(ctx context.Context) *ListApplicationReleasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list application releases params
func (o *ListApplicationReleasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list application releases params
func (o *ListApplicationReleasesParams) WithHTTPClient(client *http.Client) *ListApplicationReleasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list application releases params
func (o *ListApplicationReleasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXWorkspaceID adds the xWorkspaceID to the list application releases params
func (o *ListApplicationReleasesParams) WithXWorkspaceID(xWorkspaceID string) *ListApplicationReleasesParams {
	o.SetXWorkspaceID(xWorkspaceID)
	return o
}

// SetXWorkspaceID adds the xWorkspaceId to the list application releases params
func (o *ListApplicationReleasesParams) SetXWorkspaceID(xWorkspaceID string) {
	o.XWorkspaceID = xWorkspaceID
}

// WithID adds the id to the list application releases params
func (o *ListApplicationReleasesParams) WithID(id string) *ListApplicationReleasesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list application releases params
func (o *ListApplicationReleasesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListApplicationReleasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Workspace-ID
	if err := r.SetHeaderParam("X-Workspace-ID", o.XWorkspaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
