// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozone-one/terraform-provider-ozone/models"
)

// ListApplicationReleasesReader is a Reader for the ListApplicationReleases structure.
type ListApplicationReleasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListApplicationReleasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListApplicationReleasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListApplicationReleasesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListApplicationReleasesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListApplicationReleasesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListApplicationReleasesOK creates a ListApplicationReleasesOK with default headers values
func NewListApplicationReleasesOK() *ListApplicationReleasesOK {
	return &ListApplicationReleasesOK{}
}

/*
ListApplicationReleasesOK describes a response with status code 200, with default header values.

OK
*/
type ListApplicationReleasesOK struct {
	Payload *models.ReleaseList
}

func (o *ListApplicationReleasesOK) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}/releases][%d] listApplicationReleasesOK  %+v", 200, o.Payload)
}
func (o *ListApplicationReleasesOK) GetPayload() *models.ReleaseList {
	return o.Payload
}

func (o *ListApplicationReleasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReleaseList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListApplicationReleasesBadRequest creates a ListApplicationReleasesBadRequest with default headers values
func NewListApplicationReleasesBadRequest() *ListApplicationReleasesBadRequest {
	return &ListApplicationReleasesBadRequest{}
}

/*
ListApplicationReleasesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListApplicationReleasesBadRequest struct {
	Payload interface{}
}

func (o *ListApplicationReleasesBadRequest) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}/releases][%d] listApplicationReleasesBadRequest  %+v", 400, o.Payload)
}
func (o *ListApplicationReleasesBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ListApplicationReleasesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListApplicationReleasesNotFound creates a ListApplicationReleasesNotFound with default headers values
func NewListApplicationReleasesNotFound() *ListApplicationReleasesNotFound {
	return &ListApplicationReleasesNotFound{}
}

/*
ListApplicationReleasesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListApplicationReleasesNotFound struct {
	Payload interface{}
}

func (o *ListApplicationReleasesNotFound) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}/releases][%d] listApplicationReleasesNotFound  %+v", 404, o.Payload)
}
func (o *ListApplicationReleasesNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ListApplicationReleasesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListApplicationReleasesInternalServerError creates a ListApplicationReleasesInternalServerError with default headers values
func NewListApplicationReleasesInternalServerError() *ListApplicationReleasesInternalServerError {
	return &ListApplicationReleasesInternalServerError{}
}

/*
ListApplicationReleasesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListApplicationReleasesInternalServerError struct {
	Payload interface{}
}

func (o *ListApplicationReleasesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /admin/app/{id}/releases][%d] listApplicationReleasesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListApplicationReleasesInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *ListApplicationReleasesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
