// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationMLVerification application m l verification
//
// swagger:model applicationMLVerification
type ApplicationMLVerification struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// enabled envs
	EnabledEnvs []string `json:"enabledEnvs"`

	// sensitivity
	Sensitivity float64 `json:"sensitivity,omitempty"`

	// wait time min
	WaitTimeMin int64 `json:"waitTimeMin,omitempty"`
}

// Validate validates this application m l verification
func (m *ApplicationMLVerification) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this application m l verification based on context it is used
func (m *ApplicationMLVerification) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationMLVerification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationMLVerification) UnmarshalBinary(b []byte) error {
	var res ApplicationMLVerification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
