// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateVariableRequest create variable request
//
// swagger:model createVariableRequest
type CreateVariableRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// env values
	EnvValues map[string]string `json:"envValues,omitempty"`

	// global
	Global bool `json:"global,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this create variable request
func (m *CreateVariableRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create variable request based on context it is used
func (m *CreateVariableRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateVariableRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVariableRequest) UnmarshalBinary(b []byte) error {
	var res CreateVariableRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
