// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateAppTemplateReq create app template req
//
// swagger:model createAppTemplateReq
type CreateAppTemplateReq struct {

	// application ID
	ApplicationID string `json:"applicationID,omitempty"`

	// bootstrap value
	BootstrapValue *TemplateBootstrapValues `json:"bootstrapValue,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this create app template req
func (m *CreateAppTemplateReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBootstrapValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateAppTemplateReq) validateBootstrapValue(formats strfmt.Registry) error {
	if swag.IsZero(m.BootstrapValue) { // not required
		return nil
	}

	if m.BootstrapValue != nil {
		if err := m.BootstrapValue.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("bootstrapValue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("bootstrapValue")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create app template req based on the context it is used
func (m *CreateAppTemplateReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBootstrapValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateAppTemplateReq) contextValidateBootstrapValue(ctx context.Context, formats strfmt.Registry) error {

	if m.BootstrapValue != nil {
		if err := m.BootstrapValue.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("bootstrapValue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("bootstrapValue")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateAppTemplateReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAppTemplateReq) UnmarshalBinary(b []byte) error {
	var res CreateAppTemplateReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
