// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatadogApplicationAPM datadog application a p m
//
// swagger:model datadogApplicationAPM
type DatadogApplicationAPM struct {

	// provider ID
	ProviderID string `json:"providerID,omitempty"`
}

// Validate validates this datadog application a p m
func (m *DatadogApplicationAPM) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datadog application a p m based on context it is used
func (m *DatadogApplicationAPM) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatadogApplicationAPM) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatadogApplicationAPM) UnmarshalBinary(b []byte) error {
	var res DatadogApplicationAPM
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
