// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DynamicResource dynamic resource
//
// swagger:model DynamicResource
type DynamicResource struct {

	// AccountId ID
	AccountID string `json:"accountID,omitempty"`

	// ClusterID ID
	ClusterID string `json:"clusterID,omitempty"`

	// group
	Group string `json:"group,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// misc data
	MiscData interface{} `json:"miscData,omitempty"`

	// Object is a JSON compatible map with string, float, int, bool, []interface{}, or
	// map[string]interface{}
	// children.
	Object interface{} `json:"object,omitempty"`
}

// Validate validates this dynamic resource
func (m *DynamicResource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dynamic resource based on context it is used
func (m *DynamicResource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DynamicResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DynamicResource) UnmarshalBinary(b []byte) error {
	var res DynamicResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
