// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ElasticApplicationAPM elastic application a p m
//
// swagger:model elasticApplicationAPM
type ElasticApplicationAPM struct {

	// provider ID
	ProviderID string `json:"providerID,omitempty"`

	// service name
	ServiceName string `json:"serviceName,omitempty"`
}

// Validate validates this elastic application a p m
func (m *ElasticApplicationAPM) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this elastic application a p m based on context it is used
func (m *ElasticApplicationAPM) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ElasticApplicationAPM) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ElasticApplicationAPM) UnmarshalBinary(b []byte) error {
	var res ElasticApplicationAPM
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
