// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MongoResourceWorkspaces mongo resource workspaces
//
// swagger:model mongoResourceWorkspaces
type MongoResourceWorkspaces struct {

	// items
	Items []string `json:"items"`
}

// Validate validates this mongo resource workspaces
func (m *MongoResourceWorkspaces) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mongo resource workspaces based on context it is used
func (m *MongoResourceWorkspaces) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MongoResourceWorkspaces) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MongoResourceWorkspaces) UnmarshalBinary(b []byte) error {
	var res MongoResourceWorkspaces
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
