// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MongoObjectIDStruct mongo object ID struct
//
// swagger:model mongoObjectIDStruct
type MongoObjectIDStruct struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this mongo object ID struct
func (m *MongoObjectIDStruct) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mongo object ID struct based on context it is used
func (m *MongoObjectIDStruct) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MongoObjectIDStruct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MongoObjectIDStruct) UnmarshalBinary(b []byte) error {
	var res MongoObjectIDStruct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
