// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRelicApplicationAPM new relic application a p m
//
// swagger:model newRelicApplicationAPM
type NewRelicApplicationAPM struct {

	// env app name
	EnvAppName map[string]string `json:"envAppName,omitempty"`

	// provider ID
	ProviderID string `json:"providerID,omitempty"`
}

// Validate validates this new relic application a p m
func (m *NewRelicApplicationAPM) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new relic application a p m based on context it is used
func (m *NewRelicApplicationAPM) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewRelicApplicationAPM) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewRelicApplicationAPM) UnmarshalBinary(b []byte) error {
	var res NewRelicApplicationAPM
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
