// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PipelineRunMLVerification pipeline run m l verification
//
// swagger:model PipelineRunMLVerification
type PipelineRunMLVerification struct {

	// message
	Message string `json:"message,omitempty"`

	// started at
	StartedAt string `json:"started_at,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this pipeline run m l verification
func (m *PipelineRunMLVerification) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pipeline run m l verification based on context it is used
func (m *PipelineRunMLVerification) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PipelineRunMLVerification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineRunMLVerification) UnmarshalBinary(b []byte) error {
	var res PipelineRunMLVerification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
