// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PipelineRunRollback pipeline run rollback
//
// swagger:model PipelineRunRollback
type PipelineRunRollback struct {

	// name
	Name string `json:"name,omitempty"`

	// pipeline ID
	PipelineID string `json:"pipelineID,omitempty"`

	// pipeline run ID
	PipelineRunID string `json:"pipelineRunID,omitempty"`
}

// Validate validates this pipeline run rollback
func (m *PipelineRunRollback) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pipeline run rollback based on context it is used
func (m *PipelineRunRollback) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PipelineRunRollback) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineRunRollback) UnmarshalBinary(b []byte) error {
	var res PipelineRunRollback
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
