// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseRunJiraApprovalStep release run jira approval step
//
// swagger:model releaseRunJiraApprovalStep
type ReleaseRunJiraApprovalStep struct {

	// issue key
	IssueKey string `json:"issueKey,omitempty"`

	// project ID
	ProjectID string `json:"projectID,omitempty"`

	// provider ID
	ProviderID string `json:"providerID,omitempty"`

	// webhook ID
	WebhookID string `json:"webhookID,omitempty"`
}

// Validate validates this release run jira approval step
func (m *ReleaseRunJiraApprovalStep) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this release run jira approval step based on context it is used
func (m *ReleaseRunJiraApprovalStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseRunJiraApprovalStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseRunJiraApprovalStep) UnmarshalBinary(b []byte) error {
	var res ReleaseRunJiraApprovalStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
