// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseRunStep release run step
//
// swagger:model releaseRunStep
type ReleaseRunStep struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// jira approval
	JiraApproval *ReleaseRunJiraApprovalStep `json:"jiraApproval,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pipeline
	Pipeline *ReleaseRunPipelineStep `json:"pipeline,omitempty"`

	// run after
	RunAfter []string `json:"runAfter"`

	// slack approval
	SlackApproval *ReleaseRunSlackApprovalStep `json:"slackApproval,omitempty"`

	// status
	Status *AppReleaseStepStatus `json:"status,omitempty"`

	// timeout
	Timeout int64 `json:"timeout,omitempty"`

	// type ID
	TypeID int64 `json:"typeID,omitempty"`

	// workspaces
	Workspaces *MongoResourceWorkspaces `json:"workspaces,omitempty"`
}

// Validate validates this release run step
func (m *ReleaseRunStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJiraApproval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePipeline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSlackApproval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkspaces(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReleaseRunStep) validateJiraApproval(formats strfmt.Registry) error {
	if swag.IsZero(m.JiraApproval) { // not required
		return nil
	}

	if m.JiraApproval != nil {
		if err := m.JiraApproval.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("jiraApproval")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("jiraApproval")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) validatePipeline(formats strfmt.Registry) error {
	if swag.IsZero(m.Pipeline) { // not required
		return nil
	}

	if m.Pipeline != nil {
		if err := m.Pipeline.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pipeline")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pipeline")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) validateSlackApproval(formats strfmt.Registry) error {
	if swag.IsZero(m.SlackApproval) { // not required
		return nil
	}

	if m.SlackApproval != nil {
		if err := m.SlackApproval.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("slackApproval")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("slackApproval")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) validateWorkspaces(formats strfmt.Registry) error {
	if swag.IsZero(m.Workspaces) { // not required
		return nil
	}

	if m.Workspaces != nil {
		if err := m.Workspaces.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workspaces")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("workspaces")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this release run step based on the context it is used
func (m *ReleaseRunStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateJiraApproval(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePipeline(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSlackApproval(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorkspaces(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReleaseRunStep) contextValidateJiraApproval(ctx context.Context, formats strfmt.Registry) error {

	if m.JiraApproval != nil {
		if err := m.JiraApproval.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("jiraApproval")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("jiraApproval")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) contextValidatePipeline(ctx context.Context, formats strfmt.Registry) error {

	if m.Pipeline != nil {
		if err := m.Pipeline.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pipeline")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pipeline")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) contextValidateSlackApproval(ctx context.Context, formats strfmt.Registry) error {

	if m.SlackApproval != nil {
		if err := m.SlackApproval.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("slackApproval")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("slackApproval")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {
		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *ReleaseRunStep) contextValidateWorkspaces(ctx context.Context, formats strfmt.Registry) error {

	if m.Workspaces != nil {
		if err := m.Workspaces.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workspaces")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("workspaces")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseRunStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseRunStep) UnmarshalBinary(b []byte) error {
	var res ReleaseRunStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
