// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseRunPipelineStep release run pipeline step
//
// swagger:model releaseRunPipelineStep
type ReleaseRunPipelineStep struct {

	// application ID
	ApplicationID string `json:"applicationID,omitempty"`

	// cluster ID
	ClusterID string `json:"clusterID,omitempty"`

	// env ID
	EnvID string `json:"envID,omitempty"`

	// pipeline ID
	PipelineID string `json:"pipelineID,omitempty"`

	// timeout
	Timeout int64 `json:"timeout,omitempty"`

	// trigger params
	TriggerParams []*PipelineParam `json:"triggerParams"`
}

// Validate validates this release run pipeline step
func (m *ReleaseRunPipelineStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTriggerParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReleaseRunPipelineStep) validateTriggerParams(formats strfmt.Registry) error {
	if swag.IsZero(m.TriggerParams) { // not required
		return nil
	}

	for i := 0; i < len(m.TriggerParams); i++ {
		if swag.IsZero(m.TriggerParams[i]) { // not required
			continue
		}

		if m.TriggerParams[i] != nil {
			if err := m.TriggerParams[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("triggerParams" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("triggerParams" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this release run pipeline step based on the context it is used
func (m *ReleaseRunPipelineStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTriggerParams(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReleaseRunPipelineStep) contextValidateTriggerParams(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TriggerParams); i++ {

		if m.TriggerParams[i] != nil {
			if err := m.TriggerParams[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("triggerParams" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("triggerParams" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseRunPipelineStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseRunPipelineStep) UnmarshalBinary(b []byte) error {
	var res ReleaseRunPipelineStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
