// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseRunStatus release run status
//
// swagger:model releaseRunStatus
type ReleaseRunStatus struct {

	// completion time
	CompletionTime string `json:"completionTime,omitempty"`

	// created time
	CreatedTime string `json:"createdTime,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// updated time
	UpdatedTime string `json:"updatedTime,omitempty"`
}

// Validate validates this release run status
func (m *ReleaseRunStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this release run status based on context it is used
func (m *ReleaseRunStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseRunStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseRunStatus) UnmarshalBinary(b []byte) error {
	var res ReleaseRunStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
