// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseRunSlackApprovalStep release run slack approval step
//
// swagger:model releaseRunSlackApprovalStep
type ReleaseRunSlackApprovalStep struct {

	// callback ID
	CallbackID string `json:"callbackID,omitempty"`

	// ts
	Ts string `json:"ts,omitempty"`

	// webhook ID
	WebhookID string `json:"webhookID,omitempty"`
}

// Validate validates this release run slack approval step
func (m *ReleaseRunSlackApprovalStep) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this release run slack approval step based on context it is used
func (m *ReleaseRunSlackApprovalStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseRunSlackApprovalStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseRunSlackApprovalStep) UnmarshalBinary(b []byte) error {
	var res ReleaseRunSlackApprovalStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
