// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TemplateBootstrapValues template bootstrap values
//
// swagger:model templateBootstrapValues
type TemplateBootstrapValues struct {

	// deployment replica
	DeploymentReplica int64 `json:"deploymentReplica,omitempty"`

	// dns
	DNS string `json:"dns,omitempty"`

	// namespace name
	NamespaceName string `json:"namespaceName,omitempty"`

	// service name
	ServiceName string `json:"serviceName,omitempty"`

	// service port
	ServicePort int64 `json:"servicePort,omitempty"`

	// service target port
	ServiceTargetPort int64 `json:"serviceTargetPort,omitempty"`

	// service type
	ServiceType string `json:"serviceType,omitempty"`
}

// Validate validates this template bootstrap values
func (m *TemplateBootstrapValues) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this template bootstrap values based on context it is used
func (m *TemplateBootstrapValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TemplateBootstrapValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplateBootstrapValues) UnmarshalBinary(b []byte) error {
	var res TemplateBootstrapValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
